//Actions
export const TOGGLE_VISIBILITY = 'e.TOGGLE_VISIBILITY'
export const DISPLAY_VISIBILITY = 'e.DISPLAY_VISIBILITY'
export const CHANGE_ALERT = 'e.CREATE_ALERT'
export const DISPLAY_ALERT = 'e.DISPLAY_ALERT'
export const CHANGE_BACKGROUND_SCENE = 'e.CHANGE_BACKGROUND_SCENE'
export const DISPLAY_BACKGROUND_SCENE = 'e.DISPLAY_BACKGROUND_SCENE'
export const AUTO_SAVE = 'e.AUTO_SAVE'